---
- name: Install htop
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  tasks:
    - name: Includes users
      ansible.builtin.include_tasks: tasks/users.yml
    - name: Includes the required packages
      ansible.builtin.include_tasks: tasks/packages.yml
    - name: Includes crontab
      ansible.builtin.include_tasks: tasks/crontab.yml
    - name: Touches a test file
      ansible.builtin.include_tasks: tasks/file.yml
    - name: PostgreSQL Client
      ansible.builtin.include_tasks: tasks/postgres-client.yml
    - name: PostgreSQL PgAdmin
      ansible.builtin.include_tasks: tasks/postgres-pgadmin.yml
