- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://www.pgadmin.org/static/packages_pgadmin_org.pub
    state: present
    keyring: /etc/apt/trusted.gpg.d/packages-pgadmin-org.gpg

- name: Configure the PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/jammy pgadmin4 main
    filename: /etc/apt/sources.list.d/pgadmin4.list
    state: present

- name: Install a list of packages
  ansible.builtin.apt:
    name: pgadmin4
    update_cache: true
